package agent

import (
	"fmt"
	"math"
	"sync"
)

// Signal represents a named dimension in the gradient field.
// Signal names are fully dynamic — generated by the LLM domain auto-generator.
// There are no hardcoded signal constants.
type Signal string

// Point represents a location in the gradient field (e.g. a code region, topic, subtask).
type Point struct {
	ID        string
	Signals   map[Signal]float64 // base signals (from seeding)
	Chemicals map[string]float64 // agent-secreted chemical gradients
	Links     []string           // IDs of linked points for diffusion

	// Stigmergic knowledge layer — shared through the environment.
	Content  string   // pre-loaded region content (file listing + samples)
	Findings []string // findings deposited by agents (other agents see these)
}

// GradientField is a thread-safe multi-dimensional signal space
// with a chemical overlay for agent-to-agent stigmergic communication.
type GradientField struct {
	mu     sync.RWMutex
	points map[string]*Point
}

// NewField creates an empty gradient field.
func NewField() *GradientField {
	return &GradientField{points: make(map[string]*Point)}
}

// AddPoint adds or replaces a point in the field.
func (f *GradientField) AddPoint(p *Point) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if p.Chemicals == nil {
		p.Chemicals = make(map[string]float64)
	}
	f.points[p.ID] = p
}

// FieldPoint returns a snapshot of the point with the given ID.
func (f *GradientField) FieldPoint(id string) (Point, bool) {
	f.mu.RLock()
	defer f.mu.RUnlock()
	p, ok := f.points[id]
	if !ok {
		return Point{}, false
	}
	cp := Point{
		ID:        p.ID,
		Links:     p.Links,
		Content:   p.Content,
		Findings:  append([]string(nil), p.Findings...),
		Signals:   make(map[Signal]float64, len(p.Signals)),
		Chemicals: make(map[string]float64, len(p.Chemicals)),
	}
	for k, v := range p.Signals {
		cp.Signals[k] = v
	}
	for k, v := range p.Chemicals {
		cp.Chemicals[k] = v
	}
	return cp, true
}

// Points returns a snapshot of all point IDs.
func (f *GradientField) Points() []string {
	f.mu.RLock()
	defer f.mu.RUnlock()
	ids := make([]string, 0, len(f.points))
	for id := range f.points {
		ids = append(ids, id)
	}
	return ids
}

// ReadSignal returns the signal value at a point.
func (f *GradientField) ReadSignal(pointID string, sig Signal) float64 {
	f.mu.RLock()
	defer f.mu.RUnlock()
	p, ok := f.points[pointID]
	if !ok {
		return 0
	}
	return p.Signals[sig]
}

// AddSignal atomically adds delta to a signal at a point.
func (f *GradientField) AddSignal(pointID string, sig Signal, delta float64) {
	f.mu.Lock()
	defer f.mu.Unlock()
	p, ok := f.points[pointID]
	if !ok {
		return
	}
	p.Signals[sig] = math.Max(0, p.Signals[sig]+delta)
}

// ── Chemical layer ──────────────────────────────────────────────────

// Secrete adds chemical concentration at a point. Clamped to [0, 1].
func (f *GradientField) Secrete(pointID, chemical string, amount float64) {
	f.mu.Lock()
	defer f.mu.Unlock()
	p, ok := f.points[pointID]
	if !ok {
		return
	}
	if p.Chemicals == nil {
		p.Chemicals = make(map[string]float64)
	}
	p.Chemicals[chemical] = math.Max(0, math.Min(1.0, p.Chemicals[chemical]+amount))
}

// Sense returns chemical concentration at a point.
func (f *GradientField) Sense(pointID, chemical string) float64 {
	f.mu.RLock()
	defer f.mu.RUnlock()
	p, ok := f.points[pointID]
	if !ok {
		return 0
	}
	return p.Chemicals[chemical]
}

// DepositFinding adds a finding to a point's stigmergic knowledge.
// Other agents at this point will see it in their next tick.
func (f *GradientField) DepositFinding(pointID, finding string) {
	f.mu.Lock()
	defer f.mu.Unlock()
	p, ok := f.points[pointID]
	if !ok {
		return
	}
	p.Findings = append(p.Findings, finding)
}

// Decay multiplies all base signals by (1 - rate).
func (f *GradientField) Decay(rate float64) {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, p := range f.points {
		for sig, val := range p.Signals {
			p.Signals[sig] = val * (1 - rate)
			if p.Signals[sig] < 0.01 {
				p.Signals[sig] = 0
			}
		}
	}
}

// DecayChemicals decays all agent-secreted chemicals.
func (f *GradientField) DecayChemicals(rate float64) {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, p := range f.points {
		for chem, val := range p.Chemicals {
			newVal := val * (1 - rate)
			if newVal < 0.01 {
				delete(p.Chemicals, chem)
			} else {
				p.Chemicals[chem] = newVal
			}
		}
	}
}

// Diffuse spreads base signals between linked points.
func (f *GradientField) Diffuse(diffusionRate float64) {
	f.mu.Lock()
	defer f.mu.Unlock()

	deltas := make(map[string]map[Signal]float64)
	for id, p := range f.points {
		deltas[id] = make(map[Signal]float64)
		for _, linkID := range p.Links {
			neighbor, ok := f.points[linkID]
			if !ok {
				continue
			}
			for sig, val := range p.Signals {
				nval := neighbor.Signals[sig]
				diff := (val - nval) * diffusionRate * 0.5
				deltas[id][sig] -= diff
				if deltas[linkID] == nil {
					deltas[linkID] = make(map[Signal]float64)
				}
				deltas[linkID][sig] += diff
			}
		}
	}

	for id, sigDeltas := range deltas {
		p := f.points[id]
		for sig, d := range sigDeltas {
			p.Signals[sig] = math.Max(0, p.Signals[sig]+d)
		}
	}
}

// DiffuseChemicals spreads chemicals between linked points.
func (f *GradientField) DiffuseChemicals(rate float64) {
	f.mu.Lock()
	defer f.mu.Unlock()

	deltas := make(map[string]map[string]float64)
	for id, p := range f.points {
		for _, linkID := range p.Links {
			neighbor, ok := f.points[linkID]
			if !ok {
				continue
			}
			allChems := make(map[string]bool)
			for c := range p.Chemicals {
				allChems[c] = true
			}
			for c := range neighbor.Chemicals {
				allChems[c] = true
			}
			for chem := range allChems {
				val := p.Chemicals[chem]
				nval := neighbor.Chemicals[chem]
				diff := (val - nval) * rate * 0.5
				if deltas[id] == nil {
					deltas[id] = make(map[string]float64)
				}
				if deltas[linkID] == nil {
					deltas[linkID] = make(map[string]float64)
				}
				deltas[id][chem] -= diff
				deltas[linkID][chem] += diff
			}
		}
	}

	for id, chemDeltas := range deltas {
		p := f.points[id]
		if p.Chemicals == nil {
			p.Chemicals = make(map[string]float64)
		}
		for chem, d := range chemDeltas {
			p.Chemicals[chem] = math.Max(0, p.Chemicals[chem]+d)
		}
	}
}

// Snapshot returns a human-readable summary of the field.
func (f *GradientField) Snapshot() string {
	f.mu.RLock()
	defer f.mu.RUnlock()
	out := ""
	for _, p := range f.points {
		out += fmt.Sprintf("  [%s]", p.ID)
		for sig, v := range p.Signals {
			if v > 0 {
				out += fmt.Sprintf(" %s=%.2f", sig, v)
			}
		}
		if len(p.Chemicals) > 0 {
			out += " chem:{"
			for c, v := range p.Chemicals {
				out += fmt.Sprintf("%s=%.2f ", c, v)
			}
			out += "}"
		}
		out += "\n"
	}
	return out
}
